name: waste_management
channels:
  - conda-forge
dependencies:
  - python=3.12
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - conda-libmamba-solver
  - pip:
    - python-dotenv
    - mkdocs
    - -e .
    - tflite-runtime